name: CustomHealthDisplay
version: '1.0'
main: me.CustomHealthDisplay
api-version: '1.20'
load: STARTUP
authors: [ RyanDusty ]
description: Utilises Duels API to display both players health on the action bar
website: https://github.com/RyanDusty
depend:
  - Duels
  - CustomCooking